[project]
name = "spatial-maker"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "depth-pro",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"

dependencies = [
    "torch>=2",
    "torchvision",
    "huggingface_hub",
    "numpy<2",
    "pillow",
    "timm",
]

[tool.uv.sources]
depth-pro = { git = "https://github.com/apple/ml-depth-pro.git" }
